### ISSUE TITLE
핫딜 바로 구매하기 클릭시 토큰이 존재하는데도 로그인이 필요하다는 알람이 뜹니다.

### ISSUE THREAD

**Issue by zzzzseong** [SportsEcho/EchoProject-FE#100]
아래 이미지 참고해주시면 감사하겠습니다.

![Screenshot 2024-01-24 at 3 28 08 PM](https://github.com/SportsEcho/EchoProject-FE/assets/117155328/34f46753-5b92-41da-b62d-82379fe818c5)

**Comment by jinyr1128** [comment]
이것은 버그로 올려져있습니다 밑에 젤 처음 이슈 ㅋㅋ빠르게 고치겠습니다.
