### ISSUE TITLE
장바구니에 상품 상세정보 및 이미지 없이 수량만 뜨는 문제가 발생합니다.

### ISSUE THREAD

**Issue by zzzzseong** [SportsEcho/EchoProject-FE#97]
아래는 참고 이미지 입니다.

![Screenshot 2024-01-24 at 11 30 35 AM](https://github.com/SportsEcho/EchoProject-FE/assets/117155328/66035d23-4849-4cee-991d-f1e5c1bb24ce)

**Comment by jinyr1128** [comment]
너굴맨이 해결했다구
